version=1.0.32
sequence=33
bundle_url=https://roscoefilburnn.github.io/score7/updates/score7-scripts-1.0.32.tar.gz
bundle_size=1440
bundle_sha256=e462f15bb00e816abab0e2208a1f39b370b47f84d27023c6e3fca53fc2b1467b
signature=mKbW/rhuMNOen9aJfIn2AJTnsLSmxCAv1wLmrOhApB0dDIrPnxkCaX7HK+/PRIPKPvEGmix2q7BoCQSGaTgzTWE4N2Bmksa0i984nShoADjRdGoGwX7cxrishaIWHgvZIrrPvTOcAFrJmOUeefezTpcTtSxskTL7NKx7he1zaLcbEjlt/tw46FpHBW7R3us8yk4Z/bF+iire00F1WTOrEa79MHPv/3+ySCub6gzHUJTfiY7kDVHo6spVFFfkS3uNy1lpehM1ysSaJYfaaYUMPscDZgS8eWMhL0IgIqDrJbLrOUhx8mBTlAsvay5fHBZ9QAjqcKyFwkvyxLREavCnSPoZ4xJgChOVYO30sLAU0JfQOjPEIx/6+gY/Yig0vG9w0YhWLV3aZu7hTEiQsX4SJJ5k1WtgSi0sspg5g6bUg51VwHg7adDcXceS2ARaK1OQ0Rdco/Yocc5h/G0eBCx7+mcrwkkI5zzsudnB7OVake307ouL3d7u3dniEWWe9VMg
